[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
# unlike targets provided by the toolchain, custom target must be specified by the path to the
# target file, relative to the root of the project
target = "x86_64-unknown-none.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"